### ISSUE TITLE
Vector erase iterator outside range

### ISSUE THREAD

**Issue by HJLebbink** [ERUD1T3/quine-mccluskey-petrick#1]
When run with VisualStudio, the algorithm hits an assertion failure: "Vector erase iterator outside range" https://github.com/ERUD1T3/quine-mccluskey-petrick/blob/867a3904171bae57863e087f50133dbcc7e57bcc/includes/quine-mccluskey-petrick.cpp#L260

**Question**: does that also happen on your setup?

**Comment by ERUD1T3** [comment]
Hi, I do not have that issue when running the algorithm. I am using a text editor and I am running the program in CLI on Ubuntu Linux. The compiler is gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0. 
I suspect it might be a use case issue so I am updating the readme to be more helpful
what input are you running it on?

**Comment by HJLebbink** [comment]
I run the example when no command line parameters are given.

I suspect a logical error and added the following guard to prevent the above mentioned assertion failure. I compile with Visual Studio 2019 (compiler 16.9.0 Preview 1.0)  
![image](https://user-images.githubusercontent.com/1561352/99731333-0e7a9700-2abe-11eb-90e4-813e4760f6f1.png)
I guess that gcc is very tolerant on deleting indices that are out of range. A similar issue exists with deleting elements while iterating a map.

When I run the example I get:

> ERROR: 867b29df: invalid index 2
> Solution: A'D' + B'C + A'B + AC'

**Comment by ERUD1T3** [comment]
Yes, I see your point. Thank you @HJLebbink for pointing it out. I will update the code accordingly.
